/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersImport } from './routes/characters'
import { Route as ApplyImport } from './routes/apply'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CharactersRoute = CharactersImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRoute,
} as any)

const ApplyRoute = ApplyImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyImport
      parentRoute: typeof rootRoute
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/characters': typeof CharactersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/characters': typeof CharactersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/characters': typeof CharactersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apply' | '/characters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/characters'
  id: '__root__' | '/' | '/apply' | '/characters'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CharactersRoute: typeof CharactersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CharactersRoute: CharactersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apply",
        "/characters"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apply": {
      "filePath": "apply.tsx"
    },
    "/characters": {
      "filePath": "characters.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
